networks:
  odoo-network:

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /storage/pg_data
      o: bind
  letsencrypt_storage:
    driver: local
    driver_opts:
      type: none
      device: /storage/letsencrypt
      o: bind
  letsencrypt_data:
    driver: local
    driver_opts:
      type: none
      device: /storage/letsencrypt/data
      o: bind
  nginx_data:
    driver: local
    driver_opts:
      type: none
      device: /storage/nginx_data
      o: bind      
  odoo1_data:
    driver: local
    driver_opts:
      type: none
      device: /storage/odoo/odoo1/data
      o: bind
  odoo1_config:
    driver: local
    driver_opts:
      type: none
      device: /storage/odoo/odoo1/config
      o: bind
  odoo1_addons:
    driver: local
    driver_opts:
      type: none
      device: /storage/odoo/odoo1/extra-addons
      o: bind
  odoo2_data:
    driver: local
    driver_opts:
      type: none
      device: /storage/odoo/odoo2/data
      o: bind
  odoo2_config:
    driver: local
    driver_opts:
      type: none
      device: /storage/odoo/odoo2/config
      o: bind
  odoo2_addons:
    driver: local
    driver_opts:
      type: none
      device: /storage/odoo/odoo2/extra-addons
      o: bind
  odoo3_data:
    driver: local
    driver_opts:
      type: none
      device: /storage/odoo/odoo3/data
      o: bind
  odoo3_config:
    driver: local
    driver_opts:
      type: none
      device: /storage/odoo/odoo3/config
      o: bind
  odoo3_addons:
    driver: local
    driver_opts:
      type: none
      device: /storage/odoo/odoo3/extra-addons
      o: bind

services:
  postgres:
    image: postgres:latest
    user: root
    container_name: postgres_db
    networks: ['odoo-network']
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRESDB}  # Default DB required for initialization
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./odoo-manager.sh:/docker-entrypoint-initdb.d/odoo-manager.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${POSTGRES_PORT}:5432"

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    user: root
    restart: unless-stopped
    networks: ['odoo-network']
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - letsencrypt_data:/data
      - letsencrypt_storage:/etc/letsencrypt
      - nginx_data:/etc/nginx

  odoo1:
    image: odoo:latest
    user: root
    container_name: ${ODOO1_INSTANCE_NAME}
    networks: ['odoo-network']
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HOST: postgres
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE: ${ODOO1_DB}
    volumes:
      - odoo1_data:/var/lib/odoo
      - odoo1_config:/etc/odoo
      - odoo1_addons:/mnt/extra-addons
      - ./odoo-entrypoint.sh:/odoo-entrypoint.sh
    ports:
      - "${ODOO1_PORT}:8069"
    entrypoint: ["/odoo-entrypoint.sh"]
    command: ["--db_host=postgres_db", "--db_port=${POSTGRES_PORT}", "--db_user=${POSTGRES_USER}", "--db_password=${POSTGRES_PASSWORD}"]

  odoo2:
    image: odoo:latest
    user: root
    container_name: ${ODOO2_INSTANCE_NAME}
    networks: ['odoo-network']
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HOST: postgres
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE: ${ODOO2_DB}
    volumes:
      - odoo2_data:/var/lib/odoo
      - odoo2_config:/etc/odoo
      - odoo2_addons:/mnt/extra-addons
      - ./odoo-entrypoint.sh:/odoo-entrypoint.sh
    ports:
      - "${ODOO2_PORT}:8069"
    entrypoint: ["/odoo-entrypoint.sh"]
    command: ["--db_host=postgres_db", "--db_port=${POSTGRES_PORT}", "--db_user=${POSTGRES_USER}", "--db_password=${POSTGRES_PASSWORD}"]

  odoo3:
    image: odoo:latest
    user: root
    container_name: ${ODOO3_INSTANCE_NAME}
    networks: ['odoo-network']
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HOST: postgres
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE: ${ODOO3_DB}
    volumes:
      - odoo3_data:/var/lib/odoo
      - odoo3_config:/etc/odoo
      - odoo3_addons:/mnt/extra-addons
      - ./odoo-entrypoint.sh:/odoo-entrypoint.sh
    ports:
      - "${ODOO3_PORT}:8069"
    entrypoint: ["/odoo-entrypoint.sh"]
    command: ["--db_host=postgres_db", "--db_port=${POSTGRES_PORT}", "--db_user=${POSTGRES_USER}", "--db_password=${POSTGRES_PASSWORD}"]